# Generated by Django 5.1.1 on 2024-09-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_citas_delete_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='servicio',
            new_name='Servicio',
        ),
    ]
